# Generated by Django 4.1.5 on 2023-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="max_request",
        ),
        migrations.AddField(
            model_name="plan",
            name="max_request_per_hour",
            field=models.IntegerField(null=True, verbose_name="Max request per hour"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="words_amount",
            field=models.IntegerField(null=True, verbose_name="Words"),
        ),
    ]
