# Generated by Django 4.1.5 on 2023-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_getstartedquestion_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getstartedquestion",
            name="question",
            field=models.TextField(null=True, verbose_name="Question"),
        ),
    ]
