# Generated by Django 4.1.5 on 2023-02-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_getstartedquestion_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="getstartedbot",
            name="user",
        ),
        migrations.AddField(
            model_name="getstartedbot",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bot",
                to="core.device",
                verbose_name="User",
            ),
        ),
    ]
