# Generated by Django 4.1.5 on 2023-02-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_getstartedbot_user_getstartedbot_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getstartedbot",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bot",
                to="core.device",
                verbose_name="Device",
            ),
        ),
    ]
