# Generated by Django 4.1.5 on 2023-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_getstartedbot_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="getstartedbot",
            name="nickname",
            field=models.CharField(default="", max_length=255, verbose_name="Nickname"),
        ),
    ]
