# Generated by Django 4.1.5 on 2023-02-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_getstartedbot_answers_getstartedanswer_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="getstartedquestion",
            name="is_final_question",
            field=models.BooleanField(default=False, verbose_name="Is final question"),
        ),
    ]
