# Generated by Django 4.1.5 on 2023-02-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_getstartedquestion_is_final_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="title",
            field=models.TextField(default="", verbose_name="Title"),
        ),
    ]
