# Generated by Django 4.1.5 on 2023-02-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_getstartedanswer_bot_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Message", "verbose_name_plural": "Messages"},
        ),
    ]
