# Generated by Django 4.1.5 on 2023-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_using_prompt",
            field=models.BooleanField(default=False, verbose_name="Is using prompt"),
        ),
    ]
