# Generated by Django 4.1.5 on 2023-02-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_conversation_is_using_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="messages",
                to="core.prompt",
                verbose_name="Prompt",
            ),
        ),
    ]
