# Generated by Django 4.1.5 on 2023-02-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_message_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="is_using_prompt",
        ),
        migrations.RemoveField(
            model_name="message",
            name="prompt",
        ),
        migrations.AddField(
            model_name="conversation",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="messages",
                to="core.prompt",
                verbose_name="Prompt",
            ),
        ),
    ]
