# Generated by Django 4.1.5 on 2023-02-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_message_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
