# Generated by Django 4.1.5 on 2023-02-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_message_hidden_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="token_cost",
        ),
    ]
