# Generated by Django 4.1.5 on 2023-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_message_token_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.TextField(null=True, verbose_name="Value"),
        ),
    ]
