# Generated by Django 4.1.7 on 2023-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_setting_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="show_in_public_lobby",
            field=models.BooleanField(default=True, verbose_name="Is public lobby?"),
        ),
    ]
