# Generated by Django 4.1.7 on 2023-02-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_conversation_show_in_public_lobby"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="words_amount",
        ),
        migrations.AddField(
            model_name="plan",
            name="is_gift",
            field=models.BooleanField(default=False, verbose_name="Is gift"),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_welcome",
            field=models.BooleanField(default=False, verbose_name="Is Welcome"),
        ),
        migrations.AddField(
            model_name="plan",
            name="tokens",
            field=models.IntegerField(null=True, verbose_name="Tokens"),
        ),
    ]
