# Generated by Django 4.1.7 on 2023-02-26 07:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0029_alter_usertransactions_amount_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserTransactions",
            new_name="UserTransaction",
        ),
    ]
