# Generated by Django 4.1.7 on 2023-02-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_rename_usertransactions_usertransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="is_gift",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="is_welcome",
        ),
    ]
