# Generated by Django 4.1.7 on 2023-02-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_plan_is_gift_remove_plan_is_welcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertransaction",
            name="is_free",
            field=models.BooleanField(default=False, verbose_name="Is Free"),
        ),
        migrations.AddField(
            model_name="usertransaction",
            name="is_gift",
            field=models.BooleanField(default=False, verbose_name="Is gift"),
        ),
    ]
