# Generated by Django 4.1.7 on 2023-02-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_usertransaction_is_free_usertransaction_is_gift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="show_in_public_lobby",
            field=models.BooleanField(default=False, verbose_name="Is public lobby?"),
        ),
    ]
