# Generated by Django 4.1.7 on 2023-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_plan_is_free_trail_plan_is_free_trial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="is_free_trial",
        ),
    ]
