# Generated by Django 4.1.7 on 2023-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_plan_promotion_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="sub_title",
            field=models.TextField(null=True, verbose_name="Subtitle"),
        ),
    ]
