# Generated by Django 4.1.7 on 2023-02-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_applewebhook"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_custom_title",
            field=models.BooleanField(default=False, verbose_name="Is custom title"),
        ),
    ]
