# Generated by Django 4.1.7 on 2023-02-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_conversation_is_custom_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="token_usage_warning",
            field=models.PositiveIntegerField(
                default=200, verbose_name="Token usage warning"
            ),
        ),
    ]
