# Generated by Django 4.1.7 on 2023-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_conversation_token_usage_warning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="history_length",
            field=models.IntegerField(default=1, verbose_name="Chat history length"),
        ),
    ]
