# Generated by Django 4.1.7 on 2023-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_conversation_is_full_memory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="is_full_memory",
            field=models.BooleanField(default=True, verbose_name="Is full memory"),
        ),
    ]
