# Generated by Django 4.1.7 on 2023-03-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_alter_conversation_is_full_memory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userplan",
            old_name="apple_transaction_id",
            new_name="original_transaction_id",
        ),
    ]
