# Generated by Django 4.1.7 on 2023-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_rename_apple_transaction_id_userplan_original_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userplan",
            name="original_transaction_id",
        ),
        migrations.AddField(
            model_name="userplan",
            name="type",
            field=models.CharField(max_length=255, null=True, verbose_name="Type"),
        ),
    ]
