# Generated by Django 4.1.7 on 2023-03-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_userplan_original_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="applewebhook",
            name="is_processed",
            field=models.BooleanField(default=False, verbose_name="Is processed"),
        ),
    ]
