# Generated by Django 4.1.7 on 2023-03-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_alter_applewebhook_json_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applewebhook",
            name="json_processed",
            field=models.TextField(default="", verbose_name="Error"),
        ),
    ]
