# Generated by Django 4.1.7 on 2023-03-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_applewebhook_json_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="applewebhook",
            name="notification_type",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Notification type"
            ),
        ),
        migrations.AddField(
            model_name="applewebhook",
            name="original_transaction_id",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Original transaction id"
            ),
        ),
    ]
