# Generated by Django 4.1.7 on 2023-03-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_applewebhook_notification_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applewebhook",
            name="notification_subtype",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Notification subtype"
            ),
        ),
    ]
