# Generated by Django 4.1.7 on 2023-03-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_usertransaction_original_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twitterai",
            name="message",
        ),
        migrations.RemoveField(
            model_name="twitterai",
            name="twitter_account",
        ),
        migrations.DeleteModel(
            name="TwitterAccount",
        ),
        migrations.DeleteModel(
            name="TwitterAI",
        ),
    ]
