# Generated by Django 4.1.7 on 2023-03-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_remove_twitterai_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="history_length",
            field=models.PositiveBigIntegerField(
                default=1, verbose_name="Chat history length"
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="show_in_public_lobby",
            field=models.BooleanField(default=True, verbose_name="Is public lobby?"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="token_usage_warning",
            field=models.PositiveBigIntegerField(
                default=500, verbose_name="Token usage warning"
            ),
        ),
    ]
