# Generated by Django 4.1.7 on 2023-03-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_alter_plan_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="sub_topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompts",
                to="core.subtopic",
                verbose_name="Sub Topic",
            ),
        ),
        migrations.AlterField(
            model_name="subtopic",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="core.topic",
                verbose_name="Topic",
            ),
        ),
    ]
