# Generated by Django 4.1.7 on 2023-03-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_remove_prompt_sub_topic_prompt_topic_delete_subtopic"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="is_feature",
            field=models.BooleanField(default=False, verbose_name="Is feature"),
        ),
    ]
