# Generated by Django 4.1.7 on 2023-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_prompt_is_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applewebhook",
            name="json_processed",
            field=models.TextField(default="", verbose_name="Json Processed"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="token_usage_warning",
            field=models.PositiveBigIntegerField(
                default=2000, verbose_name="Token usage warning"
            ),
        ),
    ]
