# Generated by Django 4.1.7 on 2023-03-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_applewebhook_json_processed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertransaction",
            name="amount",
            field=models.BigIntegerField(default=0, null=True, verbose_name="Amount"),
        ),
    ]
