# Generated by Django 4.1.7 on 2023-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_alter_usertransaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboarding",
            name="sub_title",
            field=models.TextField(default="", verbose_name="Subtitle"),
        ),
    ]
