# Generated by Django 4.1.7 on 2023-03-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_onboarding_sub_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["order"],
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.AddField(
            model_name="topic",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
