# Generated by Django 4.1.7 on 2023-03-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_alter_topic_options_topic_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prompt",
            options={
                "ordering": ["order"],
                "verbose_name": "Prompt",
                "verbose_name_plural": "Prompts",
            },
        ),
        migrations.AddField(
            model_name="device",
            name="onesignal",
            field=models.CharField(
                max_length=255, null=True, verbose_name="OneSignal id"
            ),
        ),
        migrations.AddField(
            model_name="prompt",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="onboarding",
            name="sub_title",
            field=models.TextField(blank=True, default="", verbose_name="Subtitle"),
        ),
    ]
