# Generated by Django 4.1.7 on 2023-03-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_alter_prompt_options_device_onesignal_prompt_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="system_prompt",
            field=models.TextField(
                blank=True, default="", verbose_name="System prompt"
            ),
        ),
    ]
