# Generated by Django 4.1.7 on 2023-03-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_prompt_system_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="show_in_public_lobby",
            field=models.BooleanField(default=False, verbose_name="Is public lobby?"),
        ),
    ]
