# Generated by Django 4.1.7 on 2023-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_topic_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="token_usage_warning",
            field=models.PositiveBigIntegerField(
                default=4000, verbose_name="Token usage warning"
            ),
        ),
    ]
