# Generated by Django 4.1.7 on 2023-04-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_alter_conversation_history_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="is_pro",
            field=models.BooleanField(default=False, verbose_name="Is pro"),
        ),
    ]
